-- ============================================================
-- 0027: members 멀티클럽 auth_user_id 정책 — 확인 완료 (no-op)
-- ============================================================
--
-- 2026-07-09 DB 직접 확인 결과, 이미 원하는 제약조건이 존재함.
--
-- 확인된 제약조건:
--   members_auth_user_id_fkey         : auth_user_id → auth.users(id)
--   members_club_id_auth_user_id_key  : UNIQUE (club_id, auth_user_id)
--   members_club_id_kakao_provider_id_key : UNIQUE (club_id, kakao_provider_id)
--
-- 확인된 인덱스:
--   members_club_id_auth_user_id_key
--   members_club_id_kakao_provider_id_key
--   members_pkey
--
-- 정책 요약:
--   - auth_user_id 전역 unique 없음 → 같은 사용자가 여러 클럽에 연결 가능
--   - kakao_provider_id 전역 unique 없음 → 동일
--   - (club_id, auth_user_id) 복합 unique → 한 클럽 안에서는 중복 연결 불가
--
-- 이 migration은 실제 DDL을 실행하지 않는다.
-- DB가 이미 MultiClub-AuthPolicy-1 목표 상태이므로 코드 변경만 반영됨.
